var ASSERT = require('assert'),

    U = require('.').util,
    loadBemjson = U.loadBemjson;

describe('basic middlewares', function () {
    var env = global.expressSetup({ path : 'test/data/views/desktop.bundles' });

    it('should generate html page with bemhtml', function (done) {

        env.case(this.test.title, function (req, res) {
            loadBemjson('./test/data/views/desktop.bundles/index/index.bemjson.js', function (err, bemjson) {
                res.render('index', { bemjson : bemjson });
            });

        }, function (error, response, body) {
            ASSERT.notEqual(body.indexOf('<!DOCTYPE'), -1);
            done();
        });

    });

    it('should fetch bemjson generated by bemtree', function (done) {

        env.case(this.test.title, function (req, res) {
            res.render('index', {
                block    : 'page',
                raw      : true,
                title    : 'Testing testing',
                index    : true,
                contacts : []
            });

        }, function (error, response, body) {
            ASSERT.notEqual(body.indexOf('"block":"contacts",'), -1);
            done();
        });

    });

    it('should fetch html generated by bemtree and bemhtml', function (done) {

        env.case(this.test.title, function (req, res) {
            res.render('index', {
                block    : 'page',
                title    : 'Testing testing',
                index    : true,
                contacts : []
            });

        }, function (error, response, body) {
            ASSERT.notEqual(body.indexOf('<div class="page"'), -1);
            done();
        });

    });

});
